#!/bin/bash

PARAM1=$1
PARAM2=$2
if [ "$PARAM1" -a "$PARAM2" ]; # Test for empty strings
then
    echo OPENWALNUT_LIBDIR $PARAM1
    echo OPENWALNUT_INCLUDE_DIR $PARAM2
    echo
else
    echo "Usage: makeAllToolboxes <OPENWALNUT_LIBDIR> <OPENWALNUT_INCLUDE_DIR>"
    echo "Not enough parameters given, exiting."
    exit;
fi
  
for i in $(ls */ -d);
do
    echo $i;
    cd $i
    mkdir -p build
    cd build
    cmake -DOPENWALNUT_LIBDIR=$PARAM1 -DOPENWALNUT_INCLUDE_DIR=$PARAM2 ../src
    make
    cd ../..
done